server:
  port: 8081

spring:
  application:
#    注册到注册中心的服务名字
    name: eureka

eureka:
  instance:
    hostname: localhost
      #续约更新时间间隔
      #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
#      lease-renewal-interval-in-seconds: 1
      #续约到期时间
      #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
#      lease-expiration-duration-in-seconds: 2        #生产环境下一般默认90s
  client:
    #需要注册服务到服务中心
    register-with-eureka: false
    #是否需要从注册中心获取信息
    fetch-registry: false
    service-url:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 关闭注册中心的自我保护机制，防止已关闭的实例无法从注册中心剔除
    enable-self-preservation: false
    # 清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 4000   #生产环境下一般默认90s

